Need review
georgyR/Android-Academy-Msk-project pull request #1
Opened 2018-09-25 09:20 UTC by username-is-null

2018-09-25 16:18 UTC, MaxHlystov commented
Привет! 
Из интересного, взял себе на заметку CardView и открытие ссылки в приложении телеграм.
Чтобы переделал: вынес из функций все параметры.

2018-09-25 22:21 UTC, PStrelchenko requested changes
В целом - очень хорошо, ты молодец!
Но требуются доработки.

2018-09-25 22:21 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
В этой домашке не нужно было использовать constraint layout =) Зачем зависимость?

2018-09-25 22:21 UTC, PStrelchenko commented on app/build.gradle
> +    testImplementation 'junit:junit:4.12'
Тестовые зависимости, так как тестов нет, можно тоже убрать.

2018-09-25 22:21 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:28.0.0-rc02'
1 - старайся отделять зависимости, которые нужны обычному коду, и тестовые зависимости. Например, обычные зависимости пиши сверху, для тестов - ниже, для инструментальных тестов (androidTest) - еще ниже.

2018-09-25 22:21 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:28.0.0-rc02'
2 - не рекомендую использовать RC-версии библиотек. Чревато неожиданными крашами и странными багами. Пока 28 версия не стабильная (а еще лучше, пока не выпустят пару патчей), лучше не брать их support версию самую последнюю.

2018-09-25 22:21 UTC, PStrelchenko commented on app/src/androidTest/java/com/androidacademy/msk/exercise2/ExampleInstrumentedTest.java
> + * Instrumented test, which will execute on an Android device.
Пустой инструментальный тест можно удалить.

2018-09-25 22:21 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +        sendMessageBtn.setOnClickListener(v -> openSmsApp());
Проверь на утечки памяти. Скорее всего после поворота у тебя лямбда останется. Вот тут - можно почитать: https://blog.mindorks.com/detecting-and-fixing-memory-leaks-in-android

2018-09-25 22:21 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +        String phoneNumberString = "+79165766299";
а) Перенеси phoneNumberString в параметр функции -- так функция станет чуть универсальнее
б) значение этого параметра вполне тянет на константу =) ее можно вынести в качестве private static final константы в этом классе, или завести специальный класс с константами.

2018-09-25 22:21 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    private void openSmsApp() {
Чтобы не захламлять этот класс, я бы сделал отдельный класс IntentUtils, куда бы вынес построение Intent-а для отправки SMS. Если бы метод вернул null - я бы понимал, что у нас нет возможности открыть приложение -- надо показать ошибку.

2018-09-25 22:21 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +            Toast.makeText(this, R.string.toast_no_sms_app, Toast.LENGTH_SHORT).show();
Вместо Toast можно использовать модный Snackbar https://material.io/design/components/snackbars.html

2018-09-25 22:21 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +        String addresses = "georgy.ryabykh@gmail.com";
1 - вынести в параметры метода
2 - значение перевести в константу
3 - метод можно вынести в IntentUtils.

2018-09-25 22:21 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +        String instagramUrl = "https://www.instagram.com/georgy.ryabykh/";
Заведи enum с приложениями. 
Что-то типа такого:

```
enum class SocialNetworkApplication {
    
    INSTAGRAM("com.instagram.android", "https://www.instagram.com/georgy.ryabykh/"),
    TELEGRAM("...", "..."),
    TELEGRAM_X("...", "...");

    private final String appPackage;
    private final String accountUrl;


}
```

И в openSpecificApp передавай константку из enum-а. 
Это и изящней, и константы будут лежать в правильном месте, а не в коде просто так.

2018-09-25 22:21 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +        String telegramPackage = "com.instagram.android";
Уверен, что у телеграма такой package name?

2018-09-25 22:21 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
Не хватает @Nullable

2018-09-27 20:13 UTC, PStrelchenko requested changes
Еще немного правок! =)

2018-09-27 20:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    public static final String EMAIL = "georgy.ryabykh@gmail.com";
Зачем тут public? Константы вроде только внутри этого класса используются.

2018-09-27 20:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    private void openEmailApp(@NonNull String email, @NonNull String subject,
Либо все параметры в одну строчку напиши, либо subject перенеси на следующую =)

2018-09-27 20:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    private boolean openSpecificApp(@NonNull String stringUrl, @NonNull String appPackage) {
Если в качестве параметра сюда передавать `@NonNull SocialNetwork socialNetwork`, не потребуется создавать кучу методов для открытия специальной соцсети.

2018-09-27 20:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    private boolean openSpecificApp(@NonNull String stringUrl, @NonNull String appPackage) {
Будет просто

```
private boolean openSpecificApp(@NonNull SocialNetwork socialNetwork) {
    String url = socialNetwork.url;
    String appPackage = socialNetwork.appPackage;

    // ...
}
```

2018-09-27 20:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/MainActivity.java
> +    private void openInstagramProfile() {
openInstagramProfile и openTelegramProfile очень похожи - сдается мне, что можно все сделать через один-единственный openSpecificApp с разными параметрами.

2018-09-27 20:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exercise2/SocialNetworkApps.java
> +    private final String appPackage;
Я бы на параметрах поставил аннотацию `@NonNull` + в параметрах конструктора + над getter-ами. Но это по желанию.

2018-09-29 19:19 UTC, PStrelchenko approved these changes
Молодец \m/

2018-10-02 17:48 UTC, merged