Feature/ex6
georgyR/Android-Academy-Msk-project pull request #5
Opened 2018-11-07 20:22 UTC by georgyR

2018-11-11 18:42 UTC, PStrelchenko requested changes
Ченджи.

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/data/Storage.java
> +        SharedPreferences sharedPreferences = context.getSharedPreferences(SHARED_PREF, MODE_PRIVATE);
Не, sharedPrefs открывать надо 1 раз.
То есть делаешь:

```
public class Storage {
       private final SharedPreferences appPrefs;

       public Storage(@NonNull Context applicationContext) {
            sharedPreferences = applicationContext.getSharedPreferences(PREF_APP_NAME, Context.Mode);
       }

       ...
}

```

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/data/database/AppDatabase.java
> +    public static AppDatabase getDatabase(Context context) {
Опять же - должен быть только 1 инстанс базы данных. Сделай синглетон.

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/Injector.java
> +        return dbAndNetworkComponent.plusNewsListComponent(new NewsListModule());
1 - а что если ты в onCreate попадешь несколько раз? 
2 - нужно очищать компоненты. Делать ссылку на компонент = null.

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/DbModule.java
> +    @DbScope
Многа скопов о_О
Обычно их все-таки штуки 3 от силы =) Singleton, ActivityScope, FragmentScope. 
Зачем так много?

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/DbModule.java
> +        AppDatabase database = Room.databaseBuilder(
Это к вопросу о том, что AppDatabase надо делать синглетоном.

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/NewsEditorModule.java
> +        return new NewsEditorPresenter(dao, currentItemId, context);
В презентере не должно быть никакого контекста. Вообще, надо стараться Presenter держать подальше от всех android классов (чтоб тестировать было проще)

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/base/BaseNewsItemPresenter.java
> +        Log.d("INJECT_DEBUG", "NewsDetailsPresenter: " + dao);
тэг - в константы

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/base/BaseNewsItemPresenter.java
> +    protected final NewsDao database;
переменная называется неправильно =)

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/dialog/LeaveWithoutSaveDialogFragment.java
> +    public interface DialogListener {
интерфейс - в низ класса =)

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/intro/IntroActivity.java
> +    private static final String DEBUG_THREAD_SLEEP = IntroActivity.class.getSimpleName();
Ну ты же помнишь, что из-за proguard это поле в тыкву превратится?

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/intro/IntroActivity.java
> +                TimeUnit.SECONDS.sleep(2);
двоечку - в константу

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_details/NewsDetailsActivity.java
> +    public NewsDetailsPresenter presenter;
Нееее, не так.
Убери аннотацию @Inject. Ты должен был сделать примерно так -- в providePresenter получаем нужный компонент + из него получаем презентер

```
@ProvidePresenter
public NewsDetailsPresenter providePresenter() {
    return DI.getNewsDetailsComponent().getNewsDetailsPresenter();
}
```

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_details/NewsDetailsActivity.java
> +            Injector.getInstance(getApplicationContext()).getNewsDetailsComponent(id).inject(this);
А это можно было не делать, можно было в `@ProvidePresenter` заинжектить

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_details/NewsDetailsPresenter.java
> +    /*@NonNull
Что за мертвый код?

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_details/NewsDetailsPresenter.java
> +                .subscribe(() -> database.deleteNewsItemById(itemId))
А почему не вот так:

```
compositeDisposable.add(
    Completable.fromCallable { database.deleteNewsItemById(itemId) }
        .subscribeOn(Schedulers.io())
        .subscribe(() -> {}, throwable -> {})
)
```

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_editor/NewsEditorActivity.java
> +    @Inject
Аналогично про ProvidePresenter

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_list/NewsListActivity.java
> +        /*if (savedInstanceState == null) {
Dead code

2018-11-11 18:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_list/NewsListPresenter.java
> +        Log.d("DAGGER_MOXY", "NewsListPresenter: new instance");
Тэг - в константы

2018-11-17 19:45 UTC, PStrelchenko requested changes
Давай уберем лишние даггеровские модули и будет прям хорошо

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/App.java
> +                e.getCause();
```
e = e.getCause();
```

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/data/Storage.java
> +    private static final String SHARED_PREF =  "com.androidacademy.msk.exerciseproject.com.data.SHARED_PREF";
```
BuildConfig.APPLICATION_ID.<your_name>
```

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/data/Storage.java
> +    public Storage(Context context) {
Думаю, здесь не нужно создавать Storage руками.
Можно повесить аннотацию `@Inject` на конструктор, и Dagger сам сможет заинжектить, что нужно.

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/AboutModule.java
> +    public IntentUtils provideIntentUtils(@NonNull Context context) {
Аналогично Storage-у -- тут можно было это не писать -- просто делаем `@Inject` над конструкторм `IntentUtils`-а.

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/IntroModule.java
> +    public Storage provideStorage(@NonNull Context context) {
Можно просто повесить аннотацию `@Inject` на конструктор `Storage`-а. И Dagger сам заинжектит что надо.

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/IntroModule.java
> +    public IntroPresenter providePresenter(@NonNull Storage storage) {
Сдается мне, и здесь можно обойтись без этого явного провайдинга. Можно обойтись аннотацией `@Inject` над конструктором.

2018-11-17 19:45 UTC, PStrelchenko commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/IntroModule.java
> +    public Storage provideStorage(@NonNull Context context) {
Но придется в зависимости прописать 
`compileOnly "javax.annotation:jsr250-api:1.0"`

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/NewsEditorModule.java
> +        return new NewsEditorPresenter(dao, currentItemId, context);
По-прежнему контекст в presenter-е

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/di/module/NewsListModule.java
> +    public NewsListPresenter providePresenter(@NonNull NYTimesApi api, @NonNull NewsDao dao) {
Можно сделать инжектом в конструктор

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/ViewVisibilitySwitcher.java
> +        View[] views = {dataView, loadingIndicatorView, errorView, emptyListView};
Почитай про varargs в Java.

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/dialog/LeaveWithoutSaveDialogFragment.java
> +        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
А чего не единой цепочкой?
Типо

```
return builder.setMessage()
                .setPositiveButton()
                .setNegative(...)
                .create()
```

?

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/intro/IntroActivity.java
> +        Injector.getInstance(getApplicationContext()).getIntroComponent().inject(this);
Я бы чуток переделал Injector. Я бы сделал в нем дополнительный статический метод - init, куда бы передал один раз application context. А потом уже бы везде писал бы `Injector.getInstance().getIntro...`

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/intro/IntroPresenter.java
> +    public IntroPresenter(Storage storage) {
`@Inject`

2018-11-17 19:45 UTC, PStrelchenkoHH commented on app/src/main/java/com/androidacademy/msk/exerciseproject/screen/news_list/NewsListPresenter.java
> +                .map(newsResponse -> NewsConverter.toDatabase(newsResponse.getResults(), section))
Вопрос - а зачем два мапа, которые возвращают один и тот же тип?

2018-11-21 15:09 UTC, merged